name: Metrics

on:
  schedule:
    - cron: "0 0 * * 0" # Every sunday at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.STATS_TOKEN }}
          user: vinayakgupta29

          base: header, activity, community, repositories, metadata

          plugin_languages: no 

          filename: metrics.svg
